name: SoccerFull Scraper

on:
  schedule:
    - cron: '0 */3 * * *'  # Every hour, on the hour (UTC)
  workflow_dispatch:  # Allow manual trigger from UI

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          python scraper.py

      - name: Commit and push results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add matches.json scraper_log.json
          git diff --staged --quiet || git commit -m "Update matches data - $(date -u)"
          git push || echo "Nothing to push"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
